### ISSUE TITLE
proplem getting past the loading screen

### ISSUE THREAD

**Issue by hurnhu** [Sanakhatun/KotlinWithRetrofit#1]
Hello, 

I'm also attempting to use Retrofit, but am currently having issues.
So i downloaded your app to help me learn.

Anyways I currently cant get past the "Loading please wait" part.
Is there anything you did locally that didnt get commited for this to work?

**Comment by Sanakhatun** [comment]
Thank you for your feedback @hurnhu. I'm still working on this something new but the above mentioned issue has been resolved. Kindly, download it and let me know if you're getting any difficulties.
